name: clinical-refiner
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - pandas=1.3.5
  - pip
  - pip:
      - rapidfuzz==2.13.7
      - spacy==3.5.4
      - en-core-web-sm @ https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.5.0/en_core_web_sm-3.5.0-py3-none-any.whl